### ISSUE TITLE
No support for IMX219?

### ISSUE THREAD

**Issue by dangtuan18** [10x-Engineers/Infinite-ISP_FPGABinaries#11]
Is there any support for Sony IMX219 image sensors?

**Comment by sohaibimran-10xe** [comment]
Support for Sony IMX219 sensor will be added soon. @talhaiqbal-10xe, @taimur-10xe please link the branch to this issue.

**Comment by taimur-10xe** [comment]
Support for IMX219 has been added. 

You can use v1.3 relevant binary file with IMX219 image sensor module or Raspberry Pi Camera Module v2 (which also has IMX219 sensor in it).

**Comment by dangtuan18** [comment]
@sohaibimran-10xe @taimur-10xe Thank you very much, I ran it successfully, it's really impressive. Can I integrate my own image processing algorithms like edge detection with your ISP?

**Comment by sohaibimran-10xe** [comment]
> @sohaibimran-10xe @taimur-10xe Thank you very much, I ran it successfully, it's really impressive. Can I integrate my own image processing algorithms like edge detection with your ISP?

Hi @dangtuan-ng , thanks a lot. We are building a community for contributes like you. Can you email at isp@10xengineers.ai to get connected. Or get in touch using the [link](https://10xengineers.ai/contact-us/).
